<?php

/**
 * Implements hook_theme().
 */
function cc_theme_theme() {
  return [];
}

/**
 * Implements hook_preprocess_field().
 */
function cc_theme_preprocess_field(&$variables) {

  if ($variables['field_name'] === 'field_image') {

    $items_count = count($variables['items']);
    
    if ($items_count % 2 == 1) {

      $variables['attributes']['class'][] = 'image-odd';
      
    } else {

      $variables['attributes']['class'][] = 'image-even';
    }
  }
}
